################ English language ##################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
  [en.permalinks]
    blog = "/:slugorcontentbasename/"

################ French language ##################
[fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
  [fr.permalinks]
    blog = "/:slugorcontentbasename/"
