############# French navigation ##############

# main menu
[[main]]
name = "Accueil"
url = "/"
weight = 1

[[main]]
name = "A propos"
url = "/about"
weight = 2

[[main]]
name = "Articles"
url = "/blog/fr/recent"
weight = 3

[[main]]
name = "Apps"
weight = 4

[[main]]
parent = "Apps"
name = "Intranet"
url = "https://intranet.raltech.school"

[[main]]
parent = "Apps"
name = "CodeRonin"
url = "https://coderonin.raltech.school"

[[main]]
parent = "Apps"
name = "Raltech Website"
url = "https://raltech.school"

[[main]]
parent = "Pages"
name = "404 Page"
url = "/404"
