############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
name = "Articles"
url = "/blog/recent"
weight = 3

[[main]]
weight = 4
name = "Apps"

[[main]]
parent = "Apps"
name = "Intranet"
url = "https://intranet.raltech.school"

[[main]]
parent = "Apps"
name = "CodeRonin"
url = "https://coderonin.raltech.school"

[[main]]
parent = "Apps"
name = "Raltech Website"
url = "https://raltech.school"


# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Elements"
url = "/elements"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
